### ISSUE TITLE
Week number not working

### ISSUE THREAD

**Issue by j4r3kb** [stuartlangridge/gnome-shell-clock-override#10]
according to http://strftime.org when I use %U or %W the week number should be printed but instead some of the currently present output is removed. For example:
before: "%F %H:%M" -> 2018-05-04 16:35
after: "%F %W %H:%M" -> pią 16:35

Ubuntu 18.04

**Comment by da2x** [comment]
You’re looking at the wrong documentation. It should be:
https://developer.gnome.org/glib/stable/glib-GDateTime.html#g-date-time-format

**Comment by stuartlangridge** [comment]
Agreed with @da2x; thanks to his pull request we're now pointing at the correct documentation.  I think that the best you can do for week number is %V, but see the docs above.

**Comment by stuartlangridge** [comment]
@da2x I'm not using Gnome, so I was a bit loath to merge a thing that I haven't myself tested. (Docs updates are OK, though.) I'd be happy for someone (you?) to take over this extension...

**Comment by da2x** [comment]
Sure. I showed interest almost a year ago and I’m still here, so I guess that makes me qualified. 😛

Please give my account co-ownership of the extension and repository. My username on GNOME Extensions is `.ext` and my username on GitHub is `da2x`. You’ll find my email address used with both services in this repository’s git log, if you need it. In case you can’t transfer the extension to a new owner, would you consider transferring your account to me? I’d like to avoid forking the existing extension entry to maintain auto-update capabilities with the existing user base. There are too many forks already.

If at all possible, I’d also really appreciate it if you would write down your release and release testing steps in [the repository wiki](https://github.com/stuartlangridge/gnome-shell-clock-override/wiki); and document and transfer any other knowledge I should have.

**Comment by stuartlangridge** [comment]
@da2x the extension doesn't seem to have been transferred to you on extensions.gnome.org; I'm waiting on that.

**Comment by da2x** [comment]
@stuartlangridge last step is to either go to https://github.com/stuartlangridge/gnome-shell-clock-override/settings and either transfer ownership to me or add me as a admin collaborator from https://github.com/stuartlangridge/gnome-shell-clock-override/settings/collaboration

**Comment by da2x** [comment]
@stuartlangridge I think I must have ran into a caching issue; couldn’t push before but it works fine now. Thanks!
