### ISSUE TITLE
Latest update (v7 for Gnome 3.28) stopped working

### ISSUE THREAD

**Issue by fcastilloec** [stuartlangridge/gnome-shell-clock-override#13]
I installed the latest update (version `7`) on Ubuntu 18.04 with Gnome Shell 3.28.2 and it broke the extension. It doesn't matter what string combination I use, none show anymore, only the patter shows rather than the time/date. Also, yes, I did restart gnome-shell after updating.
Here's a screenshot of the topbar showing the output of some code that used to work until the new version was updated:
![selection_005](https://user-images.githubusercontent.com/1280530/43125875-16083b02-8ee0-11e8-9d78-91f15ef4d1ea.png)

I've had to manually install version `3` which it's supposed to be for Gnome 3.18 and that works on my system.
Let me know if there's anything I can do to help debug this.

**Comment by da2x** [comment]
Thanks for the report. An update with a fix was pushed a few hours ago and is pending review.

**Comment by fcastilloec** [comment]
Thanks, I've manually edited the file on my system with your fix and I can report it's working now.

**Comment by da2x** [comment]
New version was just published.
