### ISSUE TITLE
Replacements not working in latest version

### ISSUE THREAD

**Issue by Fitzsimmons** [stuartlangridge/gnome-shell-clock-override#16]
I just updated to the latest version and replacements are no longer working, making the extension completely useless.

![image](https://user-images.githubusercontent.com/418066/43208230-f276d054-8ff7-11e8-819d-270b631248ea.png)

Ubuntu 16.04

**Comment by da2x** [comment]
Duplicate of #13.

**Comment by Fitzsimmons** [comment]
Ah thanks. Might make sense to leave the other issue open until the fix is _released_.
