### ISSUE TITLE
[Request] Add unit tests

### ISSUE THREAD

**Issue by brandl-muc** [stuartlangridge/gnome-shell-clock-override#25]
I'm not at all js savvy nor would I know how to achieve this, but I think it might by a good idea to add tests to the project to avoid that the plugin breaks like with #13 . The bare minimum seems to be to test `overrider()` in extension.js

Any ideas or comments on this?

**Comment by da2x** [comment]
Refactor plan to make things more easily testable:
* move format processing out of `overrider()` to separate formatting function. Format function should return fully formatted strings.
* create `GLib.DateTime` in `overrider()` and supply it to the new formatting function. Means we can supply a mock DateTime and do direct string comparisons of what comes out of the formatter function.
* probably separate out each individual formatter extension in their own functions also.

**Comment by brandl-muc** [comment]
That sounds like a very good plan.

Meanwhile I found this: [Is there any way to write unit tests for GNOME-Shell extensions](https://stackoverflow.com/q/39063827/1969455)
This gives rise to some questions:
- I'd like to add travis support, but for our repo you would need to activate that of course. So if you're not going to do this I can as well not add support. Opinion?
- How do you deploy your extension?
- In consequence, would it be possible to change the directory structure to having a src and a test directory just as in the linked [power-alt-tab](https://github.com/emerinohdz/power-alt-tab)?

**Comment by brandl-muc** [comment]
All right, quite busy these last months (a wedding and a move) and I just gave it a first try.
See PR #30 ...

**Comment by brandl-muc** [comment]
Created PR #33 to include my tests, feel free to critique.

However since this needs [jasmine-gjs](https://github.com/ptomato/jasmine-gjs) just as [power-alt-tab](https://github.com/emerinohdz/power-alt-tab) does, I didn't add anything to the makefile yet. It does not seem sensible to check out and install jasmine-gjs by issuing a makefile command. Suggestions are very welcome, otherwise we can also leave it like is. This works well for local execution and Travis integration should be easy. (hopefully)

Next step would be breaking the `format` function down to smaller functions as you suggested, afterwards I would propose to close the issue.
