### ISSUE TITLE
Internet time is wrong

### ISSUE THREAD

**Issue by tuberculo** [stuartlangridge/gnome-shell-clock-override#26]
Internet time is not correct. 
It should be @000 on 00:00 UTC+1, instead it is on 00:00 UTC+2.

**Comment by da2x** [comment]
Which version are you running? The initial version used UTC instead of UTF+01:00. The current version use UTC+01:00 (BMT):

    GLib.TimeZone.new('+01')

Which time zone are you in? I’m not sure how this could be anything other than UTC+01

**Comment by tuberculo** [comment]
It is version 9. My time zone is UTC-3.

**Comment by tuberculo** [comment]
I've changed this line:
`var beat_time = 0 | (((bmtnow.get_hour() + 1) % 24) + bmtnow.get_minute() / 60 + bmtnow.get_second() / 3600) * 1000 / 24;`

to:
`var beat_time = 0 | (((bmtnow.get_hour()) % 24) + bmtnow.get_minute() / 60 + bmtnow.get_second() / 3600) * 1000 / 24;`

Seems to be right now.

**Comment by da2x** [comment]
Thanks!
