### ISSUE TITLE
Multi Monitor AddOn support?

### ISSUE THREAD

**Issue by Skillzore** [stuartlangridge/gnome-shell-clock-override#29]
I am using a [gnome extension to display the top bar on all my monitors](https://github.com/spin83/multi-monitors-add-on). This extension only changes the date for the main monitor. Would it be possible to make this support multiple monitors somehow?

**Comment by da2x** [comment]
This would have to be fixed in the multi-monitor add-on. I provided det[ails on where the format setting can be read from](https://github.com/spin83/multi-monitors-add-on/issues/68#issuecomment-440854052) if the developer of that extension is interested in adding support.
