### ISSUE TITLE
Bell icon not displaying anymore

### ISSUE THREAD

**Issue by farzadmf** [stuartlangridge/gnome-shell-clock-override#35]
Hi,

I was having fun :) with this good extension, and I really liked the bell icon, but for some reason, I'm not able to see that icon any more :(

In my taskbar, I see blank, like this:
![image](https://user-images.githubusercontent.com/5768792/51445710-51a72b80-1cd6-11e9-974c-a1bfee53169a.png)

And, when I open the settings, it's now like this:
![image](https://user-images.githubusercontent.com/5768792/51445688-215f8d00-1cd6-11e9-9a18-d378d088e0d2.png)

And this happens while I was able to see the bell icon before.

Thank you in advance.

**Comment by da2x** [comment]
This is likely an issue with your custom font.

**Comment by farzadmf** [comment]
@da2x can you please explain a bit more? How can I troubleshoot this? Because it was working fine, but I don't know how it started to appear as blank. Which font do you mean by "custom font"?

Thank you

**Comment by da2x** [comment]
Unicode emojis require that you have a compatible font installed. I see you've customized your desktop quite a bit, including replacing the default Cantarell font face. Double-check that you have installed a font that support emojis. Double-check that you haven't installed a font that display blank emojis. Try resetting all your GNOME desktop customization.

**Comment by farzadmf** [comment]
@da2x You were right! I have installed `font-manager`, and in its settings, I had enabled `Antialias`:
![image](https://user-images.githubusercontent.com/5768792/51451612-23d8db80-1d04-11e9-8a4c-d9b1ff09e386.png)

which apparently causes the bell icon to go away.

Can you tell me why that's happening, or is there a way to enable antialiasing to have smoother fonts, *and* be able to see the icon, because, to be honest, fonts look much smoother.

This is the "normal" font:
![image](https://user-images.githubusercontent.com/5768792/51451559-d3617e00-1d03-11e9-9cd5-ea611acefcf9.png)

And this is the antialias one:
![image](https://user-images.githubusercontent.com/5768792/51451575-ebd19880-1d03-11e9-8cc1-9bf67c244f95.png)

The second one looks much better, I think. It would be great if I could have the best of both worlds :)

**Comment by farzadmf** [comment]
Thank you @da2x for your very quick replies. Closing this one as you have addressed my issue :+1:
