### ISSUE TITLE
Extension on gnome.org is corrupt

### ISSUE THREAD

**Issue by arcooke** [stuartlangridge/gnome-shell-clock-override#41]
See below:

![image](https://user-images.githubusercontent.com/6278400/62418773-f663d780-b62e-11e9-915e-097b241181a0.png)

Cheers

**Comment by arcooke** [comment]
Completely forgot system details.. Firefox stable 65.0.1 on Solus GNOME

**Comment by da2x** [comment]
You’re trying to install a GNOME Shell extension as a Firefox extension. That will never work. I don’t really understand how you even got Firefox to think that a GNOME extension was a Firefox extension.

You need to install the [GNOME Shell extension for Firefox](https://addons.mozilla.org/en-US/firefox/addon/gnome-shell-integration/) before you can install extensions from https://extensions.gnome.org

Alternatively, you can try to install it via the GNOME Web (“epiphany”) browser.
