### ISSUE TITLE
Building from source gives version 10, but latest is 12, extensions app says

### ISSUE THREAD

**Issue by echaskaris** [stuartlangridge/gnome-shell-clock-override#49]
Ubuntu 20.04

**Comment by echaskaris** [comment]
And it auto updates too, so if the version 12 is older than the newly built 10 there is a problem. Maybe update the extension in gnome-software and/or gnome extensions website.

**Comment by da2x** [comment]
I had to reupload and had to increase the version number for some technical reason with the upload process itself. There is no other difference in the website and repo versions. I must have forgotten to commit that change.

Sorry about the confusion!
