### ISSUE TITLE
[REQUEST] Add sub-beats to main .beats time value

### ISSUE THREAD

**Issue by japkov** [stuartlangridge/gnome-shell-clock-override#55]
Hello and thanks for this handy extension - so far is the only one which can display Internet time.

Two sites https://beats.wiki/ and http://www.swatchclock.com/ feature beats "seconds" or sub-beats, centibeats as [wikipedia article](https://en.wikipedia.org/wiki/Swatch_Internet_Time#Beats) describes these - it would be cool to have these provided by extension as well - if it's of course possible to do so.

**Comment by da2x** [comment]
Modern desktops don’t display seconds to reduce the number of screen updates. It’s an energy saving feature. Knowing the background, do you still want this feature? How much precision would you need? .beats is mostly useful today as a universal ordination time within teams. Do you really need sub-beat precision to arrange your meetings?

**Comment by japkov** [comment]
I come here to suggest a feature that would enhance this extension a bit more since it already includes quite large variety of displaying preferences and the last thing I want is to being lectured on "energy saving". If that's too much to ask for then forgive me for bothering you guys and your precious time. If you care so much about wasting energy then don't reply to issues you find pointless.

Thanks for nothing
