### ISSUE TITLE
Help-link in Settings leads to incorrect page

### ISSUE THREAD

**Issue by paddylandau** [stuartlangridge/gnome-shell-clock-override#64]
In the Settings, there is a link, "What do all these %x codes mean?"

This leads to a [Github document page](https://docs.gtk.org/glib/#g-date-time-format) with an anchor `g-date-time-format`.

Unfortunately, it looks like the intended link no longer exists, as there is no such anchor or documentation on the target page. I have tried to find out where it should lead, but I have failed!

I believe that some of the `%` codes are the same as described in the Linux command `date`, but not all. E.g., `%;cf`, `%;@` and others.

Please would you update the link?

**Comment by da2x** [comment]
I can’t update the link. The GTK project has deleted this part of their documentation. It contained a lot of Glib specific time formats. So, … hm. The Internet Archive doesn’t have it either.

**Comment by paddylandau** [comment]
Oh, well. Thanks for trying, though.

Maybe leave a link to [date](https://man7.org/linux/man-pages/man1/date.1.html), but with a note that it's not exhaustive?

**Comment by Johann-Tree** [comment]
The correct link is https://docs.gtk.org/glib/method.DateTime.format.html

**Comment by paddylandau** [comment]
> The correct link is https://docs.gtk.org/glib/method.DateTime.format.html

Thank you! I have made a note of this.

@da2x — Would you be able to update the link to this one?

**Comment by da2x** [comment]
Thanks, I’ll update the link.
